# Generated by Django 5.0.2 on 2024-06-26 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("storage_management", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="file",
            name="file_format",
            field=models.CharField(default=None, max_length=50),
        ),
    ]
