# Generated by Django 5.0.2 on 2024-06-29 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("storage_management", "0003_fileaccess"),
    ]

    operations = [
        migrations.AddField(
            model_name="file",
            name="file_size",
            field=models.FloatField(default=0),
        ),
    ]
